nav:
  - index.md
  - policies.md
  - filesystems.md
  - specifications.md
  - "Getting Started": steps
  - "Software": software
  - "Datasets": datasets.md
  - "Advanced topics": advancedtopics
  - "Departments": departments
