.deploy: &deploy
  image: python:latest
  before_script:
    - pip install --user --upgrade -r requirements.txt
    - pip install -e .
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tue.nl/hpclab/website-cluster.git cluster

build:
  <<: *deploy
  stage: build
  script:
    - 'python3 -m mkdocs build --no-directory-urls --site-dir public'
    - 'echo "Preview URL: $PUBLIC_URL"'
  artifacts:
    paths:
      - public
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: "https://$CI_PROJECT_NAMESPACE.pages.tue.nl/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  variables:
    PUBLIC_URL: "https://$CI_PROJECT_NAMESPACE.pages.tue.nl/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

pages:
  <<: *deploy
  stage: deploy
  script:
    - 'python3 -m mkdocs build --site-dir public'
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
