.deploy: &deploy
  image: python:latest
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install -e .
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.tue.nl/hpclab/website-cluster.git cluster

build:
  <<: *deploy
  stage: build
  script:
    - 'mkdocs build --no-directory-urls --site-dir static'
    - 'echo "Preview URL: $PUBLIC_URL"'
  artifacts:
    paths:
      - static
  variables:
    PUBLIC_URL: "https://$CI_PROJECT_NAMESPACE.pages.tue.nl/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/static/index.html"
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'

deploy:
  <<: *deploy
  stage: deploy
  script:
    - 'mkdocs build --site-dir public'
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
