authors:
  r.j.zoontjens@tue.nl:
    name: Zoontjens, Richard
    description: HPC & AI Lead
    avatar: https://media.licdn.com/dms/image/C4D03AQEPSp7icbGzDw/profile-displayphoto-shrink_200_200/0/1586052847610?e=1704931200&v=beta&t=IozvAKLracXS9joMFQcG7sTQ7XwMS3h4JoqP70jjQ3c
  "r.kotian@tue.nl":
    name: Kotian, Roshan
    description: ML/AI application specialist
    avatar: https://media.licdn.com/dms/image/C5603AQEIQq33x_1KKg/profile-displayphoto-shrink_200_200/0/1517699698818?e=1704931200&v=beta&t=_1S3B0UW7bqww-FOGcPO61BRy0_modZNiNoZQJQ6hSk
