authors:
  "r.j.zoontjens@tue.nl":
    name: Zoontjens, Richard
    description: HPC & AI Lead
    avatar: https://media.licdn.com/dms/image/C4D03AQEPSp7icbGzDw/profile-displayphoto-shrink_200_200/0/1586052847610?e=1704931200&v=beta&t=IozvAKLracXS9joMFQcG7sTQ7XwMS3h4JoqP70jjQ3c
  "r.kotian@tue.nl":
    name: Kotian, Roshan
    description: ML/AI application specialist
    avatar: https://media.licdn.com/dms/image/C5603AQEIQq33x_1KKg/profile-displayphoto-shrink_200_200/0/1517699698818?e=1704931200&v=beta&t=_1S3B0UW7bqww-FOGcPO61BRy0_modZNiNoZQJQ6hSk
  "a.van.hoof@tue.nl":
    name: Hoof, Alain van
    description: Cluster Administrator
    avatar: https://media.licdn.com/dms/image/C4E03AQH32YPxMzFfzA/profile-displayphoto-shrink_200_200/0/1517672633165?e=1704931200&v=beta&t=C7IWAbamLfTrZXjuO4RvvOel7NITnwZ-nbZ9nHG8kC8
  "a.c.m.bertens@tue.nl":
    name: Bertens, Guus
    description: Quantum Computing / Cluster Administrator
    avatar: https://media.licdn.com/dms/image/D4E03AQHJ4BG6x-qXHg/profile-displayphoto-shrink_200_200/0/1673884243808?e=1704931200&v=beta&t=dc5FPGtvjaG435-NsbmI58uZtn6aixSVskywbUiYftM
  "e.loomeijer@tue.nl":
    name: Loomeijer, Emily
    description: Cluster Administrator
    avatar: https://media.licdn.com/dms/image/C5603AQHrCMEqas0GGw/profile-displayphoto-shrink_200_200/0/1600112280175?e=1704931200&v=beta&t=CFMMxh_ILm_ZbuPAWNww4KHywMq0S3zYpp3_kRDLjZw