| Key Length | Fingerprint                                        | Hostname   | Key Type           |
|------------|----------------------------------------------------|------------|--------------------|
| 256        | SHA256:4+mAJLnlvzJxodrsm2gHLuL+xZUUE+p3csWY9vUpaYo | hpc.tue.nl | ECDSA              |
| 256        | SHA256:Gev3AI5J7V9NWZRjmEfouU37ygEpIyF4pGSYumJ+lIc | hpc.tue.nl | ED25519            |
| 3072       | SHA256:iQY0NCJzN+P22vrBcqSX8jEYofGZd8TDKZrAv4c5hQ0 | hpc.tue.nl | RSA                |
