nav:
  - 1. Installation Prod: installation.md
  - 2. Installation Test: test installation
  - 3. Node Provisioning: provisioning.md
  - 4. Infiniband: infiniband.md
  - 5. MIG: mig.md
  - 6. Users : users.md
  - 7. SMTP : smtp.md
  - 8. SLURM: slurm.md
  - 9. VIP HA: keepalived.md
  - 10. NTP HA: ntp.md
  - 11. DNS HA : dns.md
  - 12. Storage: storage.md
  - 13. Software: modules.md
  - ...
