nav:
  - 1. Installation: installation.md
  - 2. Node Provisioning: provisioning.md
  - 3. Infiniband: infiniband.md
  - 4. Users : users.md
  - 5. SMTP : smtp.md
  - 6. SLURM: slurm.md
  - 7. VIP HA: keepalived.md
  - 8. NTP HA: ntp.md
  - 9. DNS HA : dns.md
  - 10. Storage: storage.md
  - 11. Software: modules.md
  - ...
