nav:
  - 1. Installation: installation.md
  - 2. Node Provisioning: provisioning.md
  - 3. VIP HA: keepalived.md
  - 4. NTP HA: ntp.md
  - 5. DNS HA : dns.md
  - 6. SMTP : smtp.md
  - 7. Users : users.md
  - ...
