authors:
  "a.c.m.bertens@tue.nl":
    name: Bertens, Guus
    description: Quantum Computing / Cluster Administrator
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/a.c.m.bertens.webp"
  "j.h.m.verbiesen@tue.nl":
    name: Verbiesen, Han
    description: Service Manager
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/j.h.m.verbiesen.webp"
  "a.van.hoof@tue.nl":
    name: Hoof, Alain van
    description: Cluster Administrator
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/a.van.hoof.webp"
  "e.loomeijer@tue.nl":
    name: Loomeijer, Emily
    description: Cluster Administrator
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/e.loomeijer.webp"
  "r.j.zoontjens@tue.nl":
    name: Zoontjens, Richard
    description: HPC & AI Lead
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/r.j.zoontjens.webp"
  "r.kotian@tue.nl":
    name: Kotian, Roshan
    description: ML/AI application specialist
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/r.kotian.webp"
  "g.t.chepuck.fernandes@tue.nl":
    name: Chepuck Fernandes, Gérson
    description: HPC Simulations Specialist
    avatar: "https://supercomputing.tue.nl/assets/images/avatars/g.t.chepuck.fernandes.webp"