name: Deploy Pages
on:
  workflow_run:
    workflows: ["Python Tests"]
    branches: [main]
    types:
      - completed

permissions:
  contents: read
  pages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  on-success:
    name: Deploy documentation
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install Python dependencies
        run: pip install -e .
      - name: Build documentation
        run: mkdocs build --clean
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
