name: build
on:
  workflow_run:
    workflows: [test]
    branches: [main, github-matrix-testing]

permissions:
  contents: write
  id-token: write
  pages: write

env:
  PYTHON_VERSION: 3.13

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python runtime
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Set up build cache
        uses: actions/cache/restore@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
          restore-keys: mkdocs-material-
      - name: Install dependencies
        run: sudo apt-get install pngquant
      - name: Install Python dependencies
        run: pip install -e .
      - name: Build documentation
        run: |
          export PYTHONPATH=$PYTHONPATH:$PWD/src
          mkdocs build --clean
          mkdocs --version
#      - name: Upload to GitHub Pages
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: site
#      - name: Deploy to GitHub Pages
#        uses: actions/deploy-pages@v4
      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          key: mkdocs-material-${{ hashfiles('.cache/**') }}
          path: .cache
