name: Python Tests
on: [push, fork]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  test:
    name: Python
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install Python dependencies
        run: pip install -e .
      - name: Build documentation
        run: mkdocs build --clean
  python:
    name: Python
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: 'pyproject.toml'
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Install Python dependencies
        run: pip install -e .
      - name: Build documentation
        run:  mkdocs build --clean
